# common elements used by other makefiles

SHELL = /bin/bash

DD = ../data
DO = ../data/original
DP = ../data/processed
DI = ../data/index
DR = ../data/results

MT = ../mathtuples
MS = ../mtextsearch
TE = ../trec_eval
SW = ../stopwords/en

ifneq ($(origin LANG),undefined)
  $(error ENV LANG - Internationalization breaks corpus generation)
endif

.PRECIOUS: $(MS)/%.exe

$(MS)/%.exe: $(MS)/src/*
	$(MAKE) -C $(MS) $(*).exe

